### PR TITLE
Update httpclient.go

### PR DESCRIPTION
**Pull request by alexsuslov**
Please, add utf8 to header.

### CODE REVIEW

**Comment by ddliu** [comment]
According to [RFC 8259](https://tools.ietf.org/html/rfc8259), adding charset parameter takes no effect for "application/json".

There are some [discussion](https://github.com/request/request/issues/383) for this problem, so I'm not very sure that it should be made as default.

What's your case to add utf8?

**Comment by ddliu** [comment]
Please check that the content you are sending is encoded properly. 

Content encoded as "UTF-8" should work fine.

**Comment by alexsuslov** [comment]
Server behavior depends on windows settings. If the basic encoding is set to cp1251 and body data without "charset" is interpreted as cp1251. If req header add charset utf-8. Server use UTF8.

**Comment by ddliu** [comment]
OK that's reasonable.

How about setting Content-type with method `WithHeader`?

```
httpclient.WithHeader("Content-Type", "application/json; charset=utf-8").PutJson(...)
```

It's not safe to make `utf-8` the default.

**Comment by alexsuslov** [comment]
r, err := httpclient.
		WithHeader("Content-Type", "application/json; charset=utf-8").
		WithCookie(&http.Cookie{
			Name:  "PARAM_AUTH_TOKEN",
			Value: Token,
		}).
		PostJson(uri, []TYPES.CommentType{comment})

not work

**Comment by ddliu** [comment]
Please update the package and try again, there are some overriding problems.

**Pull request closed without merging**
